### PR TITLE
Save as onnx

### PR DESCRIPTION
**Pull request by asp188**
## Motivation and Context

I have use org.bytedeco.javacpp-presets in my JAVA application to do Deep learning task in production env, and it can use onnx as a pre-trained model. So, I make this PR to copy the model as a .onnx file after it was converted from pytorch-type model.

## How Has This Been Tested

my test code under JAVA applciation is as belows:

`

        onnx.OpSchemaVector allSchemas = onnx.OpSchemaRegistry.get_all_schemas();
        System.out.println(allSchemas.size());

        byte[] bytes = Files.readAllBytes(Paths.get("/Users/qibaoyuan/Documents/source/project/pycharm/pytext/minlpdemo/ner/model.pt.prd.2.onnx"));

        onnx.ModelProto model = new onnx.ModelProto();
        ParseProtoFromBytes(model, new BytePointer(bytes), bytes.length);

        check_model(model);

        InferShapes(model);

        onnx.StringVector passes = new onnx.StringVector("eliminate_nop_transpose", "eliminate_nop_pad", "fuse_consecutive_transposes", "fuse_transpose_into_gemm");
        Optimize(model, passes);

        check_model(model);

        ConvertVersion(model, 8);

        System.out.println(model.graph().input_size());

`

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bethebunny** [comment]
This change is to create a copy of the onnx model file that has the suffix ".onnx", correct? There are a couple of ways to accomplish this now without code changes:

1. Add this copy to your builds between when you call pytext export and when you execute your java code
2. Update your config json file, change export_caffe2_path to change the name to be "whatever.onnx"
3. Change the path in your Java code to reference the file that you are exporting in your config rather than that file plus the .onnx suffix

I think all of these things are preferable to changing the code to duplicate model files, which can be quite large.

**Comment by seayoung1112** [comment]
@bethebunny the exported model file is a C2 model file rather than the original ONNX file, the ONNX file is not supposed to be big since no vocab is in it. We reuse the same "export_path" param to store the ONNX file temporarily and override it with the final C2 file. The assumption was ONNX file itself doesn't have much value without the str2id ops prepended. But if users do need the raw ONNX file, it should be done either implicitly in this PR or explicitly by adding a config param like onnx_export_path

**Comment by asp188** [comment]
> @bethebunny the exported model file is a C2 model file rather than the original ONNX file, the ONNX file is not supposed to be big since no vocab is in it. We reuse the same "export_path" param to store the ONNX file temporarily and override it with the final C2 file. The assumption was ONNX file itself doesn't have much value without the str2id ops prepended. But if users do need the raw ONNX file, it should be done either implicitly in this PR or explicitly by adding a config param like onnx_export_path

You are right, and I hope the maintainer should reconsider my PR and make an additional parameter is preferable.

**Comment by seayoung1112** [comment]
@asp188 feel free to add an additional "export_onnx_path" param to config, I can merge your PR once it's updated

**Comment by qibaoyuan** [comment]
> @asp188 feel free to add an additional "export_onnx_path" param to config, I can merge your PR once it's updated

I have make another PR in https://github.com/facebookresearch/pytext/pull/182

**Pull request closed without merging**
