### PR TITLE
Add mentioning of mixed precision training support

### PR DESCRIPTION
**Pull request by khoa-ho**
Summary: Add documentation to highlight support for mixed precision training (#611)

### CODE REVIEW

**Comment by Titousensei** [comment]
Thanks for the PR. Please fix build_docs so we can include it.

**Comment by khoa-ho** [comment]
@Titousensei Thank you for reaching out. I'm not very familiar with build_docs, do you have any hint why it might fail?

**Comment by Titousensei** [comment]
I think build_docs is was broken in master when you submitted your PR. Please try rebasing to  the most recent master.

**Comment by khoa-ho** [comment]
@Titousensei Rebasing to most recent master did get rid of the ` build_docs` error. Please help merge the PR. Thank you!

**Pull request closed without merging**
